
  0%|                                                                                        | 0/77075 [00:00<?, ?it/s]Traceback (most recent call last):
  File "C:\Users\Nova18\Documents\QLLaVA\train.py", line 94, in <module>
    fire.Fire(main)
  File "C:\Users\Nova18\anaconda3\envs\tensor\lib\site-packages\fire\core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\Users\Nova18\anaconda3\envs\tensor\lib\site-packages\fire\core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "C:\Users\Nova18\anaconda3\envs\tensor\lib\site-packages\fire\core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "C:\Users\Nova18\Documents\QLLaVA\train.py", line 76, in main
    trainer.train()
  File "C:\Users\Nova18\anaconda3\envs\tensor\lib\site-packages\transformers\trainer.py", line 1624, in train
    return inner_training_loop(
  File "C:\Users\Nova18\anaconda3\envs\tensor\lib\site-packages\transformers\trainer.py", line 1928, in _inner_training_loop
    for step, inputs in enumerate(epoch_iterator):
  File "C:\Users\Nova18\anaconda3\envs\tensor\lib\site-packages\accelerate\data_loader.py", line 452, in __iter__
    current_batch = next(dataloader_iter)
  File "C:\Users\Nova18\anaconda3\envs\tensor\lib\site-packages\torch\utils\data\dataloader.py", line 631, in __next__
    data = self._next_data()
  File "C:\Users\Nova18\anaconda3\envs\tensor\lib\site-packages\torch\utils\data\dataloader.py", line 1346, in _next_data
    return self._process_data(data)
  File "C:\Users\Nova18\anaconda3\envs\tensor\lib\site-packages\torch\utils\data\dataloader.py", line 1372, in _process_data
    data.reraise()
  File "C:\Users\Nova18\anaconda3\envs\tensor\lib\site-packages\torch\_utils.py", line 722, in reraise
    raise exception
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Users\Nova18\anaconda3\envs\tensor\lib\site-packages\torch\utils\data\_utils\worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\Nova18\anaconda3\envs\tensor\lib\site-packages\torch\utils\data\_utils\fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "C:\Users\Nova18\anaconda3\envs\tensor\lib\site-packages\transformers\trainer_utils.py", line 773, in __call__
    return self.data_collator(features)
  File "C:\Users\Nova18\anaconda3\envs\tensor\lib\site-packages\transformers\data\data_collator.py", line 92, in default_data_collator
    return torch_default_data_collator(features)
  File "C:\Users\Nova18\anaconda3\envs\tensor\lib\site-packages\transformers\data\data_collator.py", line 131, in torch_default_data_collator
    features = [vars(f) for f in features]
  File "C:\Users\Nova18\anaconda3\envs\tensor\lib\site-packages\transformers\data\data_collator.py", line 131, in <listcomp>
    features = [vars(f) for f in features]
TypeError: vars() argument must have __dict__ attribute